(() => {
  const { cfg, root, reduced } = window.Portfolio;
  const projects = cfg.projects;
  const path = slug => `${root}projects/${slug}/index.html`;
  const grid = document.querySelector("#project-grid");
  grid.innerHTML = projects.map(project => `<a data-transition class="project-grid__card" href="${path(project.slug)}" style="--project-accent:${project.accent}"><div class="project-grid__art">${project.short}</div><span class="eyebrow">${project.index} / ${project.status}</span><h3>${project.name}</h3><p>${project.tagline}</p><span class="editorial-link">Read the case study ↗</span></a>`).join("");
  const stage = document.querySelector("#card-stage"), copy = document.querySelector("#selector-copy");
  let current = 0;
  const renderCards = () => {
    stage.innerHTML = projects.map((p, offset) => { const i = (current + offset) % projects.length; const item = projects[i]; return `<article class="swipe-card" data-index="${offset}" data-slug="${item.slug}" tabindex="${offset ? -1 : 0}" style="--project-accent:${item.accent}"><div class="swipe-card__art"><span>${item.short}</span><small>${item.platform}</small></div><div class="swipe-card__body"><h3>${item.name}</h3><span class="status-badge ${item.released ? "" : "is-progress"}">${item.status}</span><p>${item.tagline}</p><a data-transition class="editorial-link" href="${path(item.slug)}">Read the case study ↗</a></div></article>`; }).join("");
    const active = projects[current]; copy.innerHTML = `<span class="eyebrow">Now reading / ${active.index}</span><h3>${active.name}</h3><p>${active.overview}</p><span class="byline">${active.role}</span>`;
    bindDrag();
  };
  const next = direction => { const top = stage.querySelector(".swipe-card"); if (window.gsap && top && !reduced) gsap.to(top, { x: direction * 720, rotation: direction * 18, opacity: 0, duration:.45, ease:"power3.in", onComplete:()=> { current = (current + 1) % projects.length; renderCards(); } }); else { current = (current + 1) % projects.length; renderCards(); } };
  function bindDrag() { const card = stage.querySelector(".swipe-card"); if (!card) return; let startX = 0, moved = 0; card.addEventListener("pointerdown", e => { startX = e.clientX; card.setPointerCapture(e.pointerId); }); card.addEventListener("pointermove", e => { if (!startX) return; moved = e.clientX - startX; card.style.transform = `translate(${moved}px, ${Math.abs(moved) * .04}px) rotate(${moved / 25}deg)`; }); card.addEventListener("pointerup", () => { if (Math.abs(moved) > 80) next(Math.sign(moved) || 1); else card.style.transform = ""; startX = moved = 0; }); card.addEventListener("keydown", e => { if (e.key === "ArrowLeft") next(-1); if (e.key === "ArrowRight") next(1); }); }
  document.querySelector("#previous-card").addEventListener("click", () => { current = (current + projects.length - 1) % projects.length; renderCards(); }); document.querySelector("#next-card").addEventListener("click", () => next(1)); document.addEventListener("keydown", e => { if (document.activeElement.closest?.(".swipe-selector") && e.key === "ArrowRight") next(1); }); renderCards();

  if (window.gsap && !reduced) { gsap.registerPlugin(ScrollTrigger); gsap.set(".hero-letter", { yPercent: 120, opacity:0 }); gsap.to(".hero-letter", { yPercent:0, opacity:1, duration:1.1, ease:"power4.out", stagger:.045, delay:1.5 }); gsap.from(".hero-photo", { clipPath:"inset(0 0 100% 0)", duration:1.1, delay:1.6, ease:"power4.inOut" }); gsap.from(".hero-photo img", { scale:1.15, duration:1.4, delay:1.6, ease:"power3.out" }); gsap.from(".hero-stamp", { scale:2, rotation:20, duration:.55, delay:2.1, ease:"back.out(2)" }); document.querySelectorAll(".display-banner h2").forEach(el => gsap.to(el, { xPercent:-22, scrollTrigger:{ trigger:el.parentElement, start:"top bottom", end:"bottom top", scrub:1 } })); document.querySelectorAll(".section-heading .line > span, .project-grid__card").forEach((el,i) => gsap.from(el, { y:45, opacity:0, duration:.7, delay:i*.04, scrollTrigger:{ trigger:el, start:"top 88%" } })); }
})();
