(() => {
  const { cfg, root, reduced } = window.Portfolio;
  const slug = document.body.dataset.theme;
  const project = cfg.projects.find(item => item.slug === slug);
  const nextProject = cfg.projects[(cfg.projects.indexOf(project) + 1) % cfg.projects.length];
  const link = target => `${root}projects/${target}/index.html`;
  const statusClass = project.released ? "" : "is-progress";
  const facts = [["Role", project.role], ["Platform", project.platform], ["Stack", project.stack.slice(0,2).join(" + ")], ["Timeframe", project.timeframe], ["Status", project.status]];
  const node = (text,x,y) => `<rect class="box" x="${x}" y="${y}" width="145" height="42"/><text x="${x+72}" y="${y+25}">${text.toUpperCase()}</text>`;
  const diagram = `<svg class="diagram" viewBox="0 0 420 310" role="img" aria-label="${project.name} architecture"><path class="line" d="M145 63H275M72 105V210M348 105V210M145 231H275"/>${node(project.architecture.nodes[0],0,42)}${node(project.architecture.nodes[1],275,42)}${node(project.architecture.nodes[2],0,210)}${node(project.architecture.nodes[3],275,210)}</svg>`;
  const action = (label,url,disabled=false) => disabled ? `<span class="button" aria-disabled="true">${label}</span>` : `<a class="button" href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
  document.querySelector("main").innerHTML = `<section class="project-hero"><div class="project-hero__inner"><span class="status-badge ${statusClass}">${project.status}</span><h1>${project.name}</h1><p class="project-hero__tagline">${project.tagline}</p><div class="facts">${facts.map(([label,value]) => `<div class="fact"><span class="meta-label">${label}</span><b>${value}</b></div>`).join("")}</div></div></section><div class="ticker"><div class="ticker__run">${Array(5).fill(`${project.name} • ${project.tagline} • `).join("")}</div></div><section class="section case-overview"><div><span class="eyebrow">Overview / 01</span><h2 class="section-heading"><span class="line"><span>The problem,</span></span><span class="line"><span>the idea.</span></span></h2></div><div><p>${project.overview}</p>${project.note ? `<p class="bio-aside" style="margin-top:28px"><strong>Note</strong>${project.note}</p>` : ""}</div></section><section class="section section-rule"><span class="eyebrow">Key features / 02</span><ol class="case-feature-list">${project.features.map((feature,i)=>`<li><span>${String(i+1).padStart(2,"0")}</span>${feature}</li>`).join("")}</ol></section><section class="display-banner"><h2>SCREEN / STUDIES /</h2></section><section class="section gallery-outer"><span class="eyebrow">Interface studies / TODO: replace with supplied project screenshots</span><div class="case-gallery">${project.gallery.map((label,i)=>`<article class="screen"><div class="screen__inside"><b>${String(i+1).padStart(2,"0")}</b><small>${label}</small></div></article>`).join("")}</div></section><section class="section section-rule architecture"><div>${diagram}</div><div><span class="eyebrow">Architecture / 03</span><h2 class="section-heading"><span class="line"><span>Systems</span></span><span class="line"><span>with a point.</span></span></h2><p class="diagram-note">${project.architecture.note}</p></div></section><section class="section section-rule"><span class="eyebrow">Tech stack / 04</span><div class="stack">${project.stack.map(item=>`<span>${item}</span>`).join("")}</div></section><section class="section section-rule"><span class="eyebrow">Links / 05</span><h2 class="section-heading"><span class="line"><span>Take a closer</span></span><span class="line"><span>look.</span></span></h2><div class="project-links">${action("Visit website", project.website, !project.website)}${project.slug === "easy-storage-cloud" ? action("Coming soon", null, true) : action("Get on Google Play", project.download, !project.download)}${project.instagram ? action("Project Instagram", project.instagram) : ""}</div></section><a data-transition class="next-project" href="${link(nextProject.slug)}"><small>Next project / ${nextProject.index}</small>${nextProject.name} ↗</a>`;
  document.title = `${project.name} — Pratham Pandey`;
  if (window.gsap && !reduced) { gsap.registerPlugin(ScrollTrigger); gsap.from(".project-hero h1", { yPercent:100, opacity:0, duration:1.15, delay:.75, ease:"power4.out" }); gsap.to(".display-banner h2", { xPercent:-22, scrollTrigger:{trigger:".display-banner", start:"top bottom", end:"bottom top", scrub:1} }); gsap.from(".case-feature-list li", { x:-35, opacity:0, stagger:.08, scrollTrigger:{trigger:".case-feature-list", start:"top 78%"} }); const gallery = document.querySelector(".case-gallery"); if (innerWidth > 820) gsap.to(gallery, { x:()=> -(gallery.scrollWidth-innerWidth+80), ease:"none", scrollTrigger:{ trigger:".gallery-outer", start:"top top", end:()=>`+=${gallery.scrollWidth}`, pin:true, scrub:1 }}); document.querySelectorAll(".diagram .line").forEach(line => { const length=line.getTotalLength(); gsap.set(line,{strokeDasharray:length,strokeDashoffset:length}); gsap.to(line,{strokeDashoffset:0,duration:1.2,scrollTrigger:{trigger:line.closest(".architecture"),start:"top 72%"}}); }); }
})();
